theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Dakar, Senegal
  <br/>
  <a href="tel:+221 77 342 65 64">ğŸ“±ğŸ‡¸ğŸ‡³ +221 77 342 65 64</a>
  <br/>
  <a href="mailto:adama.coly66@gmail.com">ğŸ“§ adama.coly66@gmail.com</a>
  <br/>
  <a href="https://github.com/adamacoly66">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/adamacoly/">ğŸ–‡ï¸ LinkedIn</a>
  I graduated from Gaston Berger University of Saint Louis, UFR (SAT).
  Having interpersonal skills and capable of gaining heights, I have skills to demonstrate in the field of computer networks, network security, system administration (Windows and Linux), mobile telecommunications, management IT projects, etc.
  I have gained experience in the field and am able to work in a team, whatever the field and environment
