theme: jekyll-theme-minimal
title: ğŸ“
description: |
  ğŸ  Dakar, Senegal
  <br/>
  <a href="tel:+221 77 342 65 64">ğŸ“±ğŸ‡¸ğŸ‡³ +221 77 342 65 64</a>
  <br/>
  <a href="mailto:adama.coly66@gmail.com">ğŸ“§ adama.coly66@gmail.com</a>
  <br/>
  <a href="https://github.com/adamacoly66">ğŸ‘¨ğŸ¾â€ğŸ’» Github</a>
  <br/>
  <a href="https://www.linkedin.com/in/adamacoly/">ğŸ–‡ï¸ LinkedIn</a>
  <br/>
  <a href="https://medium.com/@sallareznov">ğŸ“ Medium</a>
